### ISSUE TITLE
optional url-shortener api support

### ISSUE THREAD

**Issue by xakrume** [bokub/nopaste#2]
please, add url-shortener button support with predefined link/domain with selfhosted 
```
urlshortener = "https://shortener.example.com/api?link="
```
and display pasted short link

**Comment by xakrume** [comment]
I understand that this goes beyond the principles where we do not store anything. But it looks like a nightmare if I post the link in a chat message. Users can still use link shorteners to send a message, but to get short links - users need to do a few additional steps

**Comment by d3r1n** [comment]
btw kutt.it is great to do this its opensource and free

**Comment by Alyetama** [comment]
```shell
$ pip install requests
$ pip install unu
$ pip install pyperclip
```
Create a python script (let's name it `shortner.py`):
```py
from unu import unu
import pyperclip

link = pyperclip.paste()
pyperclip.copy(unu(url=link, action="shorturl", format="simple"))
```

Then run the command like this:
```shell
echo -n 'Hello Short World!' | lzma | base64 | xargs -0 printf "https://nopaste.ml/#%s\n" | pbcopy && python3 shortner.py
```

**Comment by ghost** [comment]
That's why I'm using paste.sh.

**Comment by jzeuzs** [comment]
You could use this: https://github.com/qntm/base65536

**Comment by xakrume** [comment]
closed because we switched to dpaste.
Nopaste offers another idea that I find uncomfortable, because the big text/code in encoding and decoding loads the CPU.
