### ISSUE TITLE
Question: How did you manage to generate links 

### ISSUE THREAD

**Issue by d3r1n** [bokub/nopaste#3]
First of all, I am impressed by [**_NoPaste_**](https://www.nopaste.ml) because I want to make a _code-editor_ for schools or teams to collaborate live.

But I have a question **How did you manage to generate links?**  I saw the app generate links by adding **'#'** and generate random id to it but when I looked at your code I did not manage to understand how you did it. Did you use a library or is it a simple thing I don't know because I'm a beginner? 😃🤔

Thank you again for your interest.

- Derin Onder Eren (d3r1n)

**Comment by bokub** [comment]
Hi,

Did you even read the [README](https://github.com/bokub/nopaste#readme) ? Especially the "[How it works](https://github.com/bokub/nopaste#how-it-works)" part ?

It explains how the string after the `#` is generated (BTW it's not random at all)

**Comment by d3r1n** [comment]
ok, I did read thanks again. BTW why you didn't advertise the **_NoPaste_** to the _community_? It's too good I really want to see it used among developers. thanks again for your interest again 😄 .

**Comment by bokub** [comment]
I would love it if NoPaste had more users! But I don't really know how "advertise" to the community. If you have anything in mind, don't hesitate to tell me

**Comment by d3r1n** [comment]
I guess **Reddit** is the right place to advertise. And you can add websites like _dev.to_, _Hashnode, Freecodecamp, HackerNews, Hackernoon_ to **_GitHub's "Sponsors"_** part if they want to add an option to embed code link that redirects to **_NoPaste_**. 

And [issue 2](https://github.com/bokub/nopaste/issues/2) is a good idea to implement and short the URLs hashed string. (a website like nopst.sh or a pre-made service works too.)

and a **_Discord_** for developers server named **NoPaste** is good too.

**NoPaste** has a lot of _potential_ to be a big **_open-source_** project. I don't want to see its wasted
