### ISSUE TITLE
Won’t let me make a paste on iOS

### ISSUE THREAD

**Issue by dillfrescott** [bokub/nopaste#5]
I can't click the main window to start typing. Tested on Safari and Firefox for iOS.

**Comment by bokub** [comment]
Unfortunately, I don't own any device running with iOS, so there is no way for me to reproduce the bug :man_shrugging: 

If someone wants to take a look, please go ahead!

**Comment by dillfrescott** [comment]
Hey thats ok I totally understand. Its not a problem

**Comment by dillfrescott** [comment]
Ill leave the issue open so maybe somebody can see it

**Comment by dillfrescott** [comment]
If you are given a paste link on iOS with text already in it you can edit it just fine. It's starting pastes that seems to be the issue.

**Comment by dillfrescott** [comment]
Ok I feel dumb. You have to tap even with the first line to be able to type. Tapping below that doesn't work. 


All is good
