### ISSUE TITLE
example.com/?l=lua#<encrypted text> redirects to example.com/?l=lua

### ISSUE THREAD

**Issue by Lucitrash-vCoder** [bokub/nopaste#9]
example.com/?l=lua#<encrypted text> redirects to example.com/?l=lua
(This problem only happens for first-entry people, because of this problem, the content is not visible.)

**Comment by Lucitrash-vCoder** [comment]
Test: https://cheatersoul.click/?l=lua#XQAAAQAdAQAAAAAAAAAW4HyGSCGw1YoeHvHOYGemwVusmOKlt0gDh9VPvmbS/zaDsKxcSN3z1Ju9bcuVdU+1Wo8X6HYVSVlFhffdPzaL2NjhqGD97F3Ejb2nwIRPV4V2nffvGsTb0aATRri6KKCsgbIK15lpAwUvGGX8iiCDgpTYN+Sg5WkVuUW+o+3HqOM1ikW1/gSr7kJLVGTn823tHTJb2c8/Yw5oThQHUPhc/EP+NrypC5mjfbXjk+FqrM4OUBTq/+sp521lC7+Zrliob6dsVf0oni4amFPxG4SIbvzFbBTp7vjnBuqM9ro2d4acbKzr2tE9ysz/d3pAAA==

**Comment by bokub** [comment]
First of all, hello?

I don't understand what your problem is, your "test" links looks good to me, there is no redirection, and I can read the code.

![image](https://user-images.githubusercontent.com/17952318/154067699-09729b46-0bc9-45f0-83b7-c6a8aef7bc6f.png)

**Comment by bokub** [comment]
By the way, I see that you re-branded every "NoPaste" with "SoulBin".

I'm kind of OK with that, but could you please at least credit my work in the "About" section? Something like this:

![image](https://user-images.githubusercontent.com/17952318/154068580-a09bac38-fc0d-4836-8cde-ff35cc3b9d13.png)

I case you don't realize, you're using my work for free, taking all the credit for it (which is forbidden by the license), and now you're asking me to help you doing that without even asking nicely? This is a little bit fucked up to be honest... :disappointed:

**Comment by Lucitrash-vCoder** [comment]
Which browser are you using? and sorry for that, i will add.

**Comment by Lucitrash-vCoder** [comment]
https://cdn.discordapp.com/attachments/763300242173984780/943135246185033838/Desktop_2022.02.15_-_16.21.42.02.DVR.mp4

**Comment by bokub** [comment]
Your problem comes from the FingerprintJS script (https://dmg0877nfcvqj.cloudfront.net/?fngmd=944532) that you added. I'm not affected because I'm using an ad-blocker.

**Comment by Lucitrash-vCoder** [comment]
Can you develop a pastebin site for me where I can use ads?

**Comment by bokub** [comment]
Why don't you run ads on your own website and embed NoPaste on this site ?

**Comment by Lucitrash-vCoder** [comment]
1. site is adsense, 2. is admaven
